// Transcrito do Catálogo Famais 2026 (páginas 2–22).
// Cada registro aponta para uma foto recortada da página correspondente.
// O PDF não informa preços nem estoque; ambos permanecem sob consulta.
const CATALOG_2026 = [
    [2, 1, "Balanço Gota Ferro", "Balanços", "ferro"],
    [2, 2, "Balanço Ninho Ferro", "Balanços", "ferro"],
    [2, 3, "Conjunto Navegantes Ferro", "Conjuntos", "ferro"],
    [3, 1, "Conjunto Marrocos Ferro", "Conjuntos", "ferro"],
    [3, 2, "Conjunto Happy Hour Ferro", "Conjuntos", "ferro"],
    [3, 3, "Conjunto Garden Alumínio Polido", "Conjuntos", "alumínio polido"],
    [4, 1, "Conjunto Salinas Alumínio Polido Vidro", "Conjuntos", "alumínio polido e vidro"],
    [4, 2, "Conjunto Salinas Ripado Alumínio Pintado", "Conjuntos", "alumínio pintado"],
    [4, 3, "Conjunto Alinaça 4 Lugares Vidro Ferro", "Conjuntos", "ferro e vidro"],
    [5, 1, "Conjunto Alinaça 6 Lugares Vidro Ferro", "Conjuntos", "ferro e vidro"],
    [5, 2, "Conjunto Alinaça 4 Lugares MDP Ferro", "Conjuntos", "ferro e MDP"],
    [5, 3, "Conjunto Alinaça 6 Lugares MDP Ferro", "Conjuntos", "ferro e MDP"],
    [6, 1, "Conjunto Cairo 4 Lugares Granito Ferro", "Conjuntos", "ferro e granito"],
    [6, 2, "Conjunto Cairo 6 Lugares Granito Ferro", "Conjuntos", "ferro e granito"],
    [6, 3, "Conjunto Veneza Alumínio Polido", "Conjuntos", "alumínio polido"],
    [7, 1, "Conjunto Panero Alumínio Polido", "Conjuntos", "alumínio polido"],
    [7, 2, "Banqueta Vigor Alumínio Polido", "Banquetas", "alumínio polido"],
    [7, 3, "Banqueta Conforto Alumínio Polido", "Banquetas", "alumínio polido"],
    [8, 1, "Banqueta Diplomata Ferro", "Banquetas", "ferro"],
    [8, 2, "Banqueta Forts Ferro", "Banquetas", "ferro"],
    [8, 3, "Banqueta Havaí Ferro", "Banquetas", "ferro"],
    [9, 1, "Banqueta Home Ferro", "Banquetas", "ferro"],
    [9, 2, "Poltrona Roma Alumínio Polido", "Poltronas", "alumínio polido"],
    [9, 3, "Poltrona Lua de Mel Ferro", "Poltronas", "ferro"],
    [10, 1, "Poltrona Porto com Descanso de Pé", "Poltronas", "alumínio pintado"],
    [10, 2, "Cadeira Balanço Bela Ferro", "Cadeiras", "ferro"],
    [10, 3, "Cadeira Balanço Paris Ferro", "Cadeiras", "ferro"],
    [11, 1, "Conjunto Ônix Ferro", "Conjuntos", "ferro"],
    [11, 2, "Conjunto Bela Ferro", "Conjuntos", "ferro"],
    [11, 3, "Conjunto Vitória Ferro", "Conjuntos", "ferro"],
    [12, 1, "Conjunto Itália Ferro", "Conjuntos", "ferro"],
    [12, 2, "Cadeira Eclipse Fio Ferro", "Cadeiras", "ferro"],
    [12, 3, "Cadeira Caribe Fio Ferro", "Cadeiras", "ferro"],
    [13, 1, "Espreguiçadeira Ilha do Mel Alumínio Polido", "Espreguiçadeiras", "alumínio polido"],
    [13, 2, "Espreguiçadeira Ipanema Alumínio Polido", "Espreguiçadeiras", "alumínio polido"],
    [15, 1, "Conjunto Marrocos Ferro — Linha Premium", "Conjuntos", "linha premium"],
    [15, 2, "Conjunto Santiago Ferro — Linha Premium", "Conjuntos", "linha premium"],
    [15, 3, "Conjunto Madri Ypê Alumínio Pintado", "Conjuntos", "alumínio pintado"],
    [16, 1, "Balanço Ninho Ferro — Linha Premium", "Balanços", "linha premium"],
    [16, 2, "Chaise Búzios Alumínio", "Chaises", "alumínio"],
    [16, 3, "Poltrona Porto com Descanso de Pé — Premium", "Poltronas", "alumínio pintado"],
    [17, 1, "Espreguiçadeira Ipanema Alumínio Polido — Premium", "Espreguiçadeiras", "alumínio polido"],
    [17, 2, "Cadeira Caribe Ferro — Premium", "Cadeiras", "ferro"],
    [17, 3, "Cadeira Eclipse Ferro — Premium", "Cadeiras", "ferro"],
    [18, 1, "Conjunto Vigor Alumínio Pintado", "Conjuntos", "alumínio pintado"],
    [20, 1, "Conjunto Santiago Ferro — Tricô Náutico", "Conjuntos", "linha premium tricô náutico"],
    [20, 2, "Balanço Ninho Ferro — Tricô Náutico", "Balanços", "linha premium tricô náutico"],
    [20, 3, "Conjunto Garden Alumínio Pintado", "Conjuntos", "alumínio pintado"],
    [21, 1, "Conjunto Portofino Alumínio Pintado", "Conjuntos", "alumínio pintado"],
    [21, 2, "Poltrona Porto com Descanso de Pé — Tricô Náutico", "Poltronas", "alumínio pintado"],
    [21, 3, "Espreguiçadeira Ipanema Alumínio Pintado", "Espreguiçadeiras", "alumínio pintado"],
    [22, 1, "Espreguiçadeira Ilha do Mel Alumínio Pintado", "Espreguiçadeiras", "alumínio pintado"],
    [22, 2, "Espreguiçadeira Itapema Alumínio Pintado", "Espreguiçadeiras", "alumínio pintado"]
];

const DEFAULT_PRODUCTS = CATALOG_2026.map(([page, row, name, category, material], index) => ({
    id: index + 101,
    reference: `F26-${String(page).padStart(2, "0")}-${row}`,
    name,
    category,
    image: `catalogo-2026-p${String(page).padStart(2, "0")}-r${row}.jpg`,
    price: null,
    stock: null,
    featured: [0, 1, 2, 3, 5, 8, 15, 24, 35, 39, 45].includes(index) ? 1 : 0,
    description: `Modelo do Catálogo Famais 2026 (${material}). Consulte medidas, acabamentos e disponibilidade no orçamento.`
}));
